### ISSUE TITLE
Support names mapping in github_issue_converter.py

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Austin503/support-tools#59]
```
In github_issue_converter.py there is the following information:

  4. (Optional) If this option is skipped all issues will be assigned to the
     owner of the repo.  Make a file that contains a mapping from the Google
     Code email address to the GitHub username for each user you wish to assign
     issues too.  The file should be newline seperated with one user per line.
     The email address and username should be colon (':') seperated. For example
     a file may look like this:
       <Google Code Email>:<GitHub Username>
       myemail@gmail.com:coolperson
       otheruser@gmail.com:userother

  5. Then run the command:
     ...
     --user_file_path="<optional-path-to-user-mapping-file>"

When using github_issue_converter.py with the --user_file_path option I got the 
following error:
  Traceback (most recent call last):
    File "/tmp/support-tools/googlecode-issues-exporter/github_issue_converter.py", line 470, in <module>
      main(sys.argv)
    File "/tmp/support-tools/googlecode-issues-exporter/github_issue_converter.py", line 466, in main
      parsed_args.rate_limit)
    File "/tmp/support-tools/googlecode-issues-exporter/github_issue_converter.py", line 415, in ExportIssues
      user_file_path, github_owner_username, user_service)
    File "/tmp/support-tools/googlecode-issues-exporter/issues.py", line 441, in LoadUserData
      user_map = json.loads(user_json)["users"]
    File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
      return _default_decoder.decode(s)
    File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
      obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
      raise ValueError("No JSON object could be decoded")
  ValueError: No JSON object could be decoded

Is the --user_file_path option currently supported in github_issue_converter.py?

```

Original issue reported on code.google.com by `andres.s...@gmail.com` on 26 Mar 2015 at 5:03

**Comment by GoogleCodeExporter** [comment]
```
Re: "Is the --user_file_path option currently supported in 
github_issue_converter.py?"

It was, and kinda-sorta-should-be, but currently isn't.

The tool was originally built with the ability to map Google Code user names to 
GitHub accounts. So that when the issue migration was done, you could properly 
assign issues to users. However, doing so generates **a lot** of spam. Imagine 
fast-fowarding years worth of issue email notifications in just a few minutes.

In addition, with the user name mapping we cannot set the "issue updated by" or 
"issue reported by" fields, since that would require the credential for the 
user's GitHub account.

So anyways, the code is still in there, although it seems like it has drifted 
since we last tested it out. This is a bug, and we should eventually support 
this feature -- albeit with disclaimers that it will spam people, and also not 
be as useful as you'd like.
```

Original comment by `chrsm...@google.com` on 26 Apr 2015 at 1:11
- Changed title: **Support names mapping in github_issue_converter.py**
- Changed state: **Accepted**
- Added labels: **Component-ExporterScripts**

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
was: User names mapping in github_issue_converter.py
```

Original comment by `birdbay...@gmail.com` on 1 Nov 2015 at 8:20
